# 2020.08.28(금)

## 1. Promise가 resolve할때까지 retry하는 Promise.retry 함수

attemps 만큼 시도해서 reject 반환 !

```
Promise.retry = function (fn, attemps) { 
	return new Promise(async (resolve,reject)=> {
		while(attemps--){
			try { 
				const res = await fn();
				resolve(res);
			} catch(err) {
				
			}
		
		
			
	}
```